### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by brandonyeoxg** [CS2103JAN2017-F12-B1/main#46]
**Regarding User Guide:**
Good job adding a Keyboard Shortcut table for easy reference.
Perhaps add more partial screenshots that captures the usage of command(s)?

The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

**Regarding Developer Guide:**
Good job adding a comprehensive product survey, perhaps it can be represented in a table?

Do make sure the the diagrams are updated to represent your task manager and not the addressbook.

_For the user stories:_
Perhaps task could be split into the three categories? Floating, deadline and event(start time and end time)?

_For the use cases:_
Under adding of task, shouldn't the list of task be shown too?
`System adds the task to a list of tasks `, perhaps it could be extended further to show a list of task?
Same goes for some of the other use cases. 

_For the glossary:_
Good job making appropriate changes to this =).

It may be more practical to give a few examples of interesting test cases and explain the thinking behind how you arrived at those test cases, rather than try to give a comprehensive list of all test cases.

Perhaps explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.

**Overall:**
Good job including extra features like shortcut and auto complete =).
Recall from tutorial about dog-fooding your product, perhaps think of ways to improve the command format? 
Also do remember to read up on the deliverable for each milestone. 
Try to do a peer review on each other's PR.
Please close this issue after reading it.

**Comment by jingloon** [comment]
thanks @brandonyeoxg !
