### ISSUE TITLE
Update relevant user guide and documentation

### ISSUE THREAD

**Issue by yeejfe** [CS2103JAN2017-F12-B1/main#48]

**Comment by yeejfe** [comment]
Update the AboutUs.md page

Example:

#### [Dennis Doe](http://www.comp.nus.edu.sg/~damithch) [@damithc](https://github.com/damithc)
<img src="http://www.comp.nus.edu.sg/~cs2103/AY1617S2/images/dennis-ritchie.png" width="150"><br>

* Components in charge of: [Storage](https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.md#storage-component)
* Aspects/tools in charge of: Testing, Git
* Features implemented:
   * [List persons](https://github.com/se-edu/addressbook-level4/blob/master/docs/UserGuide.md#listing-all-persons--list)
   * [Delete person](https://github.com/se-edu/addressbook-level4/blob/master/docs/UserGuide.md#deleting-a-person--delete)
* Code written: [[functional code](A123456.md)][[test code](A123456.md)]
* Other major contributions:
  * Did the initial refactoring from AddressBook to ToDoList [[#133](https://github.com/se-edu/addressbook-level4/pull/152) ]
  * Set up Travis and Coveralls 

#### Jane Doe @janedoe

**Comment by jingloon** [comment]
done for my part, will add more after this week
